In [1]:
print("hello world")

hello world


In [2]:
import os
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [60]:
my_data = ""
with open('/content/drive/MyDrive/faqs.txt', 'r') as f:
    for line in f:
        my_data+=line.strip()


In [6]:
my_data

'Did you eat breakfast today and I had paratha with tea in the morning. I am going to university because my class starts at nine. My mom is feeling better now and I am thankful for that. I will bring tomatoes on my way home. I prayed Fajr because I woke up early today. I want something simple for lunch like rice and curry. It is raining heavily outside and the weather changed so suddenly. I am excited to watch the cricket match and I would not miss it. I have an extra notebook in my bag so you can take it. It will take around fifteen minutes to reach there.I want to meet today but I am busy until evening. I talked to the teacher and she will send the notes. I am going to the market to buy a few things. My parcel has not arrived yet and maybe it will come tomorrow. I am watching a drama on TV right now. I am almost done with my assignment and just checking it once more. I think we should order food because I am really hungry. The bus was very crowded and I had to stand the whole way. I 

In [7]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [61]:
tokenizer = Tokenizer()

In [62]:
tokenizer.fit_on_texts([my_data])

In [63]:
len(tokenizer.word_index)

324

In [64]:
# Split Sentences on the Base of comma(.)
input_sequences = []
for sentence in my_data.split('.'):
  print(sentence)
  input_sequences.append(sentence)

Did you eat breakfast today and I had paratha with tea in the morning
 I am going to university because my class starts at nine
 My mom is feeling better now and I am thankful for that
 I will bring tomatoes on my way home
 I prayed Fajr because I woke up early today
 I want something simple for lunch like rice and curry
 It is raining heavily outside and the weather changed so suddenly
 I am excited to watch the cricket match and I would not miss it
 I have an extra notebook in my bag so you can take it
 It will take around fifteen minutes to reach there
I want to meet today but I am busy until evening
 I talked to the teacher and she will send the notes
 I am going to the market to buy a few things
 My parcel has not arrived yet and maybe it will come tomorrow
 I am watching a drama on TV right now
 I am almost done with my assignment and just checking it once more
 I think we should order food because I am really hungry
 The bus was very crowded and I had to stand the whole way
 I c

In [65]:
#Sentence mapping Structure
for i in input_sequences:
  tokenized_sentence =i.split(' ')
  print(tokenized_sentence)
  for x in range(1,len(tokenized_sentence)):
    print(tokenized_sentence[:x+1])


['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha', 'with', 'tea', 'in', 'the', 'morning']
['Did', 'you']
['Did', 'you', 'eat']
['Did', 'you', 'eat', 'breakfast']
['Did', 'you', 'eat', 'breakfast', 'today']
['Did', 'you', 'eat', 'breakfast', 'today', 'and']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha', 'with']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha', 'with', 'tea']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha', 'with', 'tea', 'in']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha', 'with', 'tea', 'in', 'the']
['Did', 'you', 'eat', 'breakfast', 'today', 'and', 'I', 'had', 'paratha', 'with', 'tea', 'in', 'the', 'morning']
['', 'I', 'am', 'going', 'to', 'university', '

In [66]:
# Prepairing the Dataset in the form of like window slider
input_sequences = []
for sentence in my_data.split('.'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [67]:
input_sequences

[[52, 11],
 [52, 11, 104],
 [52, 11, 104, 105],
 [52, 11, 104, 105, 16],
 [52, 11, 104, 105, 16, 5],
 [52, 11, 104, 105, 16, 5, 1],
 [52, 11, 104, 105, 16, 5, 1, 31],
 [52, 11, 104, 105, 16, 5, 1, 31, 106],
 [52, 11, 104, 105, 16, 5, 1, 31, 106, 22],
 [52, 11, 104, 105, 16, 5, 1, 31, 106, 22, 32],
 [52, 11, 104, 105, 16, 5, 1, 31, 106, 22, 32, 17],
 [52, 11, 104, 105, 16, 5, 1, 31, 106, 22, 32, 17, 2],
 [52, 11, 104, 105, 16, 5, 1, 31, 106, 22, 32, 17, 2, 53],
 [1, 3],
 [1, 3, 23],
 [1, 3, 23, 9],
 [1, 3, 23, 9, 107],
 [1, 3, 23, 9, 107, 12],
 [1, 3, 23, 9, 107, 12, 4],
 [1, 3, 23, 9, 107, 12, 4, 108],
 [1, 3, 23, 9, 107, 12, 4, 108, 109],
 [1, 3, 23, 9, 107, 12, 4, 108, 109, 24],
 [1, 3, 23, 9, 107, 12, 4, 108, 109, 24, 54],
 [4, 110],
 [4, 110, 10],
 [4, 110, 10, 55],
 [4, 110, 10, 55, 111],
 [4, 110, 10, 55, 111, 18],
 [4, 110, 10, 55, 111, 18, 5],
 [4, 110, 10, 55, 111, 18, 5, 1],
 [4, 110, 10, 55, 111, 18, 5, 1, 3],
 [4, 110, 10, 55, 111, 18, 5, 1, 3, 112],
 [4, 110, 10, 55, 111, 

In [68]:
# we have to find max length of our Sentences
max_len = max([len(x) for x in input_sequences])
print(max_len)

14


In [69]:
from keras.preprocessing.sequence import pad_sequences
padding_sentence = pad_sequences(input_sequences,maxlen= max_len,padding = 'pre')


In [70]:
print(padding_sentence[0])

[ 0  0  0  0  0  0  0  0  0  0  0  0 52 11]


In [71]:
x = padding_sentence[:,:-1]
y = padding_sentence[:,-1]

In [72]:
x.shape

(721, 13)

In [73]:
y.shape

(721,)

In [74]:
x[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 52], dtype=int32)

In [75]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=325)

In [24]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [76]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [97]:
model = Sequential()
model.add(Embedding(325, 100, input_shape=(13,1)))
model.add(LSTM(150))
model.add(LSTM(150))
# model.add(LSTM(150))  # Optional second LSTM (you can use return_sequences=True above for stacking)
model.add(Dense(325, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


ValueError: Input 0 of layer "lstm_11" is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 13, 1, 100)

In [84]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [80]:
import numpy as np
x.shape
x = np.reshape(x, (x.shape[0], x.shape[1], 1))


In [109]:
vocab_size = 325

# model = Sequential()
# model.add(LSTM(150, return_sequences=True, input_shape=(13,1)))
# model.add(LSTM(150))
# model.add(Dense(128, activation='relu'))
# model.add(Dense(vocab_size, activation='softmax'))


model = Sequential()
# model.add(Embedding(input_dim=vocab_size, output_dim=100, input_length=13))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(150))
model.add(Dense(128, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [111]:
model.fit(x,y,epochs=200,verbose=True,batch_size=32)

Epoch 1/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.1501 - loss: 3.8256
Epoch 2/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.1252 - loss: 3.7430
Epoch 3/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.1640 - loss: 3.5005
Epoch 4/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.1647 - loss: 3.3665
Epoch 5/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.1876 - loss: 3.2160
Epoch 6/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.1986 - loss: 3.0933
Epoch 7/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - accuracy: 0.2230 - loss: 2.9372
Epoch 8/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.2567 - loss: 2.7965
Epoch 9/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.2806 - loss: 2.6474
Epoch 10/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.3397 - loss: 2.5472
Epoch 11/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.3300 - loss: 2.4597
Epoch 12/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step

In [104]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_12 (LSTM)                  │ (None, 13, 150)        │        91,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_13 (LSTM)                  │ (None, 150)            │       180,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 128)            │        19,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 325)            │        41,925 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 999,161 (3.81 MB)

 Trainable params: 333,053 (1.27 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 666,108 (2.54 MB)

In [112]:
import numpy as np

def predict_next_word(model, tokenizer, text, seq_length=14):
    """
    Given some text, predicts the next word using the trained LSTM model.
    """
    # 1️⃣ Convert text to sequence of integers
    sequence = tokenizer.texts_to_sequences([text])[0]

    # 2️⃣ Pad or trim the sequence to match training length
    if len(sequence) < seq_length:
        sequence = [0]*(seq_length - len(sequence)) + sequence  # pad at start
    else:
        sequence = sequence[-seq_length:]  # keep last seq_length tokens

    sequence = np.array(sequence).reshape(1, seq_length)

    # 3️⃣ Predict probabilities for next word
    pred_probs = model.predict(sequence, verbose=0)

    # 4️⃣ Get index of most likely next word
    predicted_index = np.argmax(pred_probs, axis=1)[0]

    # 5️⃣ Convert index back to word
    for word, index in tokenizer.word_index.items():
        if index == predicted_index:
            return word

# Example usage:
text = "I want to meet today but i am busy until"
next_word = predict_next_word(model, tokenizer, text)
print(f"Next word suggestion: {next_word}")
# I want to meet today but I am busy until evening.

Next word suggestion: evening


In [113]:
# model.save("next_word_model.h5")
# Save model to Google Drive
model.save('/content/drive/MyDrive/next_word_model.h5')

In [114]:
import pickle

# Assume 'tokenizer' is your trained Keras Tokenizer
with open('/content/drive/MyDrive/tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)
